#!/usr/bin/python
import sys


class operator:
    _op_list=list("+-/x")


    def __init__(self, op:  str):
        if op not in self._op_list:
            raise ValueError
        self.op = op

    def __str__(self):
        if self.op == "x":
            return "*"
        return self.op


def printUsage():
    print("Usage: calc NUMBER1 OPERATOR NUMBER2")

def printHelp():
    printUsage()
    print("")
    print("First argument must be anumber")
    print("Second argument must be an operator*")
    print("Third argument must be a number")
    print("")
    print("")
    print(" --help          bring up this message")
    print(" --usage         bring up the usage guide")
    print("")
    print("")
    print("*one of the following is considered an operator:")
    for i in operator._op_list:
        print(f" {i}", end="")
    print("")




def inputCheck():
    try:
        if sys.argv[1] == "--usage":
            printUsage()
            sys.exit();
        if sys.argv[1] == "--help":
            printHelp()
            sys.exit()

        if not sys.stdin.isatty():
            In = sys.stdin.read()
            sys.argv.insert(1, In)


        if len(sys.argv) != 4:
            printHelp()
            sys.exit()
    except IndexError:
        printHelp()
        sys.exit()


def Calc():
    try:
        num1 = float(sys.argv[1])
    except ValueError:
        sys.exit("1st argumens is not a number")

    try:
        op = operator(sys.argv[2])
    except ValueError:
        sys.exit("2nd argument must be an operator")

    try:
        num2 = float(sys.argv[3])
    except ValueError:
        sys.exit("3rd argument must be a number")


    execstr = "print(" + str(num1) + str(op) + str(num2) + ')'
    exec(execstr)


if __name__ == "__main__":
    inputCheck()
    Calc()
