#!/bin/bash
for i in {0..32}; do
    for j in {0..32}; do
        for k in {0..32}; do
            printf "\x1b[38;2;"$(($i * 8))";"$(($j * 8))";"$(($k * 8))"m#\x1b[0m"
        done
    done
done
printf "\n"

