#!/bin/sh

failMsg(){
    echo no directory "$1"
    exit 1
}
CURRENT=$PWD
cd "$1" 2>/dev/null || failMsg "$@"
eval "$(echo "$@" | sed 's/[\/\.\_a-zA-Z0-9\-]* \(.*\)/\1/')"

if cd "$CURRENT"
then
    exit 0
else
    echo soemthing went very very wrong
    exit 1
fi

