#!/bin/bash
from=$1  #  Find files that have names like something.text
to=$2    #  Change the .text suffix to .txt

find . -type f -name "*.$from" -exec sh -c 'mv "$3" "${3%.$1}.$2"' sh "$from" "$to" {} ';'

