#!/bin/bash
# Temporarily change which tty the output goes to (Does not support &, &&, |, ||)

# Save curernt tty
TTY=$(tty)
TTY=${TTY##*/}

# start directing all output from this tty to the first argument to the function
exec 1>/dev/pts/$1

# execute the second argument
${*:2}

# return to outputing to the current tty
exec 1>/dev/pts/$TTY
